### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Arnauete02** [Arnauete02/ABP1_Firebase_Toni_Arnau#4]
**Describe brevemente cuál será la función de la nueva pantalla**
Una imagen inicial a vuestro gusto. Siempre podéis poner el logo de l'Escola del Treball.

**¿Relación con otras pantallas?**
Sí, Login Screen & Home Screen (en el caso de que se inicie con _SharedPreferences_).

**Contexto adicional**
Se debe mostrar este splash aunque el usuario esté iniciado en el _SharedPreferences_.

**Comment by ToniCarpa** [comment]
Activity Done!
Splash con transición
Nuevo PULL trabajo final
